### ISSUE TITLE
[NEW BENCHMARK] depth_image_proc

### ISSUE THREAD

**Issue by jasonjabbour** [robotperf/benchmarks#17]
**Specify the ROS2 package are you benchmarking:**
depth_image_proc

**Provide the link to the ROS2 package:**
https://github.com/ros-perception/image_pipeline/tree/humble/depth_image_proc

**Which category does your benchmark fall under?**
- [x] Perception
- [ ] Localization
- [ ] Control 
- [ ] Navigation
- [ ] Manipulation

**What metric are you benchmarking?**
latency (ms)

**What is your estimated date of completion?**
May 2nd, 2023

**What hardware will your reference implementation run on?**

- 12th Gen Intel(R) Core(TM) i9-12900KF
-  NVIDIA GeForce RTX 3080 Ti

**Your organization:**
Harvard University

**Your name:**
Jason Jabbour

**Your email address or contact information:**
jasonjabbour@g.harvard.edu

**Comment by jasonjabbour** [comment]
Yep! I've built the computational graph, here's what it looks like:

![computational graph](https://user-images.githubusercontent.com/55008744/234099119-0a2cb21c-c635-405e-b3ad-cb65bdf50d77.png)

I still need to add a tracepoint for the output node and analyze the data!

**Comment by vmayoral** [comment]
Awesome, if you push it into a PR, happy to make a first pass and review it tomorrow, as I'll be allocating time for it.

**Comment by vmayoral** [comment]
@jasonjabbour would be great to get this added as `a6`, note there's been new benchmark also added. We're starting to get speed :).

**Comment by vmayoral** [comment]
I believe this was addressed. Closing.
