### ISSUE TITLE
[NEW BENCHMARK] imu_transformer

### ISSUE THREAD

**Issue by jasonjabbour** [robotperf/benchmarks#215]
Specify the ROS2 package are you benchmarking:
imu_transformer

Provide the link to the ROS2 package:
[https://github.com/ros-perception/imu_pipeline/tree/ros2/imu_transformer](https://github.com/ros-perception/imu_pipeline/tree/ros2/imu_transformer)

Which category does your benchmark fall under?
- [x]  Perception
- [ ]  Localization
- [ ]  Control
- [ ]  Navigation
- [ ]  Manipulation

What metric are you benchmarking?
latency, power, throughput

What is your estimated date of completion?
July 18th, 2023

What hardware will your reference implementation run on?
12th Gen Intel(R) Core(TM) i9-12900KF

Your organization:
Harvard University

Your name:
Jason Jabbour

Your email address or contact information:
[jasonjabbour@g.harvard.edu](mailto:jasonjabbour@g.harvard.edu)

**Comment by vmayoral** [comment]
Closing here @jasonjabbour, feel free to re-open if you're still working on this and would like it active.
