### ISSUE TITLE
power_msgs package for ROS2 Humble

### ISSUE THREAD

**Issue by jasonjabbour** [robotperf/benchmarks#237]
Hi! I am trying to use the [robotperf ros2_benchmark repo](https://github.com/robotperf/ros2_benchmark) to create the auto.launch.py script for the a6 benchmark. It seems like the ros2_benchmark package[ depends on ](https://github.com/robotperf/ros2_benchmark/blob/bfce108da7d60c77fd2e021b731db6f06f29198a/ros2_benchmark/package.xml#L44)the power_msgs package. 

However, I can't seem to find the Humble version of power_msgs. 

<img width="460" alt="image" src="https://github.com/robotperf/benchmarks/assets/55008744/28cfa999-ee3f-43ba-a3f9-231a32987ebb">

Any tips about how I can install this package?

<img width="278" alt="image" src="https://github.com/robotperf/benchmarks/assets/55008744/11dcbc54-c4ac-41a5-be33-ee56914f15d6">

Thanks!!

**Comment by vmayoral** [comment]
@jasonjabbour, `power_msgs` used for obtaining Power readings is propietary. Our implementation has been made vendor-agnostic and can capture power from NVIDIA, AMD, Intel, Qualcomm and a few other vendors. There're no current plans for disclosing it. 

You can either create your own Power.msg and power reading implementation (see https://github.com/ros-acceleration/ros2_kria/tree/main/ros2_kria_power if you need an open source inspiration) and/or discard reading power simply.

**Comment by vmayoral** [comment]
Closing here.
