### ISSUE TITLE
a1_perception_node not reproducable

### ISSUE THREAD

**Issue by sacchinbhg** [robotperf/benchmarks#35]
Hey, so I had the following doubts after going through the [benchmark repo](https://github.com/robotperf/benchmarks) thoroughly. 

1) The steps given [here](https://github.com/robotperf/benchmarks/blob/main/benchmarks/TEMPLATE.yaml) are not reproducible. A github [issue](https://github.com/robotperf/benchmarks/issues/1) of the same exists and points to the solution [here](https://github.com/robotperf/benchmarks/tree/main/benchmarks/perception/a1_perception_2nodes). Following the solution we get this output:

![image](https://github.com/robotperf/benchmarks/assets/61612220/e7a1bc9b-c343-4a61-84ec-7d97ad80d3e3)

![image (1)](https://github.com/robotperf/benchmarks/assets/61612220/2218f599-145e-4662-8662-fda96b367c11)

![image (2)](https://github.com/robotperf/benchmarks/assets/61612220/0c8c6e96-45be-4171-85a3-b9c05e82ef4a)

The documentation does not explain what to do after this. There is a /input node which I am not sure if the rosbag should attach too or something else. Is there a ros bag that you guys have?

2) If I do ro2 node info /image_input_component this is what I get

![image (3)](https://github.com/robotperf/benchmarks/assets/61612220/4e312a3d-f2f8-4f17-94b8-13e6b3937424)

I do not understand why the node is subscribing to the topic "/camera/camera_info" and publishing to "/camera/camera_info". 

3) If I publish a rosbag to send data to "/camera/camera_info" and "/camera/image_raw". This happens:
image.png

![image (4)](https://github.com/robotperf/benchmarks/assets/61612220/c2dc141c-d840-4ba6-a5aa-307b9a22c741)

This is due to the image_input_component node publishing and subscribing to the same camera_info. This leads to more camera_info messages coming than camera_rawImages. If you guys can clarify why this happens it would help a lot. Anyhow even with this working it does not seem like I am getting the result as shown in the github.

If you can let me know what the next steps are from here, it would help a lot. Thank you for the same

**Comment by mcres** [comment]
Perhaps the steps described for `a3` benchmark are more detailed: https://github.com/robotperf/benchmarks/blob/main/benchmarks/perception/a3_stereo_image_proc/benchmark.yaml. For the moment, you can easily extrapolate the steps needed for your particular case.

Can you please confirm if you are getting traced data in `~/.ros/tracing/a1_perception_2nodes` using `babeltrace2` as explained in the link above?

If so, you should be able to run `ros2 launch a1_perception_2nodes analyze_a1_perception_2nodes.launch.py` and get some latency metrics and plots of your node.

**Comment by vmayoral** [comment]
> The steps given [here](https://github.com/robotperf/benchmarks/blob/main/benchmarks/TEMPLATE.yaml) are not reproducible. A github https://github.com/robotperf/benchmarks/issues/1 of the same exists and points to the solution [here](https://github.com/robotperf/benchmarks/tree/main/benchmarks/perception/a1_perception_2nodes). Following the solution we get this output:

You're pointing to the TEMPLATE, of course that's not expected to be reproducible.

I'd recommend reviewing the comments from others and/or to join the ROS 2 HAWG meetings. There's quite a few people working on this and confirming it is reproducible. Moreover this is running in an automated manner daily.

**Comment by sacchinbhg** [comment]
Hey, so I now tried the a3 node. The steps there were quiet easy to understand. Sorry for that.

Everything works fine until this step:
`babeltrace a3_stereo_image_proc | less`
This is the output for that command. Which I think means the trace launch file works well and good.
![image](https://github.com/robotperf/benchmarks/assets/61612220/45c00099-9280-49a2-a605-911f17d5b2be)

But when I try 
`ros2 launch a3_stereo_image_proc analyze_a3_stereo_image_proc.launch.py`
I get this output:
![image](https://github.com/robotperf/benchmarks/assets/61612220/66665dd4-ce7d-4f36-a151-e6debc8d6292)
Also if I do `ros2 node list` I get this:
![image](https://github.com/robotperf/benchmarks/assets/61612220/64b1ce60-00bd-4917-bd6c-4f205d88edaf)
Why are there 2 nodes with the same name? Am I doing something wrong? 

I will join the next weekly meeting for sure. If there is anything else I can do till then it would really help me out.

**Comment by vmayoral** [comment]
Closing this ticket. `a1`'s confirmed and fully reproducible across compute platforms. See https://news.accelerationrobotics.com/robotperf-alpha/ for some public results with data digested.

See https://github.com/robotperf/benchmarks/releases/tag/alpha for the complete alpha release.

**Comment by smilefish110** [comment]
> Hey, so I now tried the a3 node. The steps there were quiet easy to understand. Sorry for that.
> 
> Everything works fine until this step: `babeltrace a3_stereo_image_proc | less` This is the output for that command. Which I think means the trace launch file works well and good. ![image](https://private-user-images.githubusercontent.com/61612220/240610537-45c00099-9280-49a2-a605-911f17d5b2be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTkzMjksIm5iZiI6MTcyODcxOTAyOSwicGF0aCI6Ii82MTYxMjIyMC8yNDA2MTA1MzctNDVjMDAwOTktOTI4MC00OWEyLWE2MDUtOTExZjE3ZDViMmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3NDM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ODdlMjZkMGEzZWM4N2EyNTQ0ZjIyN2NhNjgwYTViNDMwNjU0NDRhNmRkM2EwMTljMzM4Mjg4NWY1YWNjZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MS-pM-PFM2QusmKMyrbwy1Z40hZLnUCv7RqKdGt8mHw)
> 
> But when I try `ros2 launch a3_stereo_image_proc analyze_a3_stereo_image_proc.launch.py` I get this output: ![image](https://private-user-images.githubusercontent.com/61612220/240611244-66665dd4-ce7d-4f36-a151-e6debc8d6292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTkzMjksIm5iZiI6MTcyODcxOTAyOSwicGF0aCI6Ii82MTYxMjIyMC8yNDA2MTEyNDQtNjY2NjVkZDQtY2U3ZC00ZjM2LWExNTEtZTZkZWJjOGQ2MjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3NDM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyOWE2NmY5Nzg5YjI1NmNkNjhmNjlhNzg5Mzg5Nzk2OGUxNzA3OGY3NDk0YzA0NTNjZTczNDI0ZmM1MTdjM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OBkD6JgDLBH9vhclyx514-Cx7LkVmZwxUwsAo4U_a4I) Also if I do `ros2 node list` I get this: ![image](https://private-user-images.githubusercontent.com/61612220/240613178-64b1ce60-00bd-4917-bd6c-4f205d88edaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTkzMjksIm5iZiI6MTcyODcxOTAyOSwicGF0aCI6Ii82MTYxMjIyMC8yNDA2MTMxNzgtNjRiMWNlNjAtMDBiZC00OTE3LWJkNmMtNGYyMDVkODhlZGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3NDM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlY2JlZjg1ODgxMTFiZWE4YTQwMjlhZmViMWQ3MGEzMmU2ODgxNDMyMTJiZDQ3ODA1OGEyZTJiNzE4MmM2MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RXRqx9PcuCvvCLf3oiOXNvlj6CyJWjx65K8cVnMwClo) Why are there 2 nodes with the same name? Am I doing something wrong?
> 
> I will join the next weekly meeting for sure. If there is anything else I can do till then it would really help me out.

Hello! Have you solved this problem? I have met a similar problem while I run the analyze_a2_rectify.launch.py. Do you know how to solve this problem? Thank you very much!

![5](https://github.com/user-attachments/assets/86a37a90-86ce-453e-b85d-f53b57c123d9)
